alias bettyall='betty *.c *.h'
alias cc='chmod +x '
alias cht='/home/vagrant/ismail/simple_shell/test_files_done/checker.bash ./hsh $1'
alias cpt='cp /home/vagrant/ismail/simple_shell/test_files_done/checker.txt .'
alias ect='echo $1'
alias excut='chmod +x !(README.md)'
alias gc='gcc -Wall -Werror -Wextra -pedantic -std=gnu89 /home/vagrant/ismail/simple_shell/*.c -o hsh'
alias gci='gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh'
alias gco='gcc -Wall -Werror -Wextra -pedantic -std=gnu89 ../*.c -o hsh'
alias gct='gcc -Wall -Werror -Wextra -pedantic -std=gnu89 /home/vagrant/ismail/simple_shell/*.c -o hsh'
alias mvc='cp /home/vagrant/ismail/simple_shell/test_files_done/checker.txt .'
alias mvt='mv /home/vagrant/shared_files/*.txt .'
